# RISC-V Bootloader: Model Compiler Output
# Generated by model_compiler.py Phase 1
#
# This assembly embeds neural network model weights and biases
# using .incbin directive. The bootloader code (Phase 2) will
# copy this embedded data to correct memory addresses.
#
# Model Type: generator
# Number of Layers: 1
# Binary Data Size: 92 bytes
#
# Memory Map:
#   0x00000 - 0x0FFFF: Bootloader code and embedded model data
#   0x10000 - 0xF3C7F: Generator model (loaded by bootloader)
#   0xF4ABC - 0xFFFFF: Recognizer model (loaded by bootloader)

.section .data
.align 4
.globl model_data_start


# Model binary data (embedded via .incbin)
# Size: 92 bytes
model_data_start:
    .incbin "blackbox_tests/neural_exec/test_simple_layer.bin"
model_data_end:

# Calculate total embedded data size
.set model_data_size, model_data_end - model_data_start



# ====== EXECUTION CODE ======


# Main execution loop: Input -> Forward Pass -> Output -> Repeat
# Mimics static_char_gen.c behavior but with neural network
.section .text
.align 4
.globl _start

_start:
    # Initialize stack pointer to safe location (within 1MB, below code/data)
    li sp, 0xF000              # sp = 0x0F000 (61440 bytes)
    
    # Main inference loop (infinite)
inference_loop:
    # Step 1: Read input and map to network input
    # For generator: a0 contains character code (set externally or hardcoded for testing)
    # For now, use a test character 'A' = 65
    li a0, 65                    # TODO: Read from external source
    call map_input_generator
    
    # Step 2: Run forward pass through all layers
    call run_forward_pass
    
    # Step 3: Map output to framebuffer
    call map_output_generator
    
    # Step 4: Loop back
    j inference_loop
    
    # Unreachable, but include exit for completeness
    li a0, 0
    li a7, 93                    # SYS_exit
    ecall



# Input mapping: Character code (a0) -> Network input
# For generator: one-hot encoding of character
map_input_generator:
    # a0 = character code (0-254)
    # Output: input buffer at 0x00150000

    lui t0, 336
    addi t0, t0, 0

    # Zero out entire input buffer (255 floats)
    li t1, 12
    xor t2, t2, t2
.Lclear_input:
    beq t2, t1, .Lclear_done
    add t3, t0, t2
    sw zero, 0(t3)
    addi t2, t2, 4
    j .Lclear_input

.Lclear_done:
    # Set input[char_code] = 1.0
    # Validate a0 is in range [0, 254]
    li t1, 255
    bgeu a0, t1, .Linput_done

    slli t1, a0, 2                  # t1 = char_code * 4
    add t1, t0, t1                  # t1 = input_buf + offset
    lui t2, 0x3F800                 # t2 = 1.0 in float
    sw t2, 0(t1)                    # input[char_code] = 1.0

.Linput_done:
    ret



# Output mapping: Network output -> Framebuffer pixels
# For generator: convert 400 floats to grayscale pixels
map_output_generator:
    # Read from output buffer at 0x00153000
    # Write to framebuffer at 0x00200000

    lui t0, 339
    addi t0, t0, 0
    lui t1, 512

    li t2, 0                        # t2 = pixel index
    li t3, 2            # t3 = num pixels (400)

.Lwrite_pixels:
    bge t2, t3, .Lwrite_done

    # Load float output[i]
    slli t4, t2, 2                  # t4 = i * 4
    add t4, t0, t4                  # t4 = output_buf + i*4
    flw fa0, 0(t4)                  # fa0 = output[i]

    # Clamp to [0.0, 1.0]
    fmv.w.x fa1, zero
    fmax.s fa0, fa0, fa1            # fa0 = max(fa0, 0.0)
    lui t5, 0x3F800                 # 1.0 in float
    fmv.w.x fa1, t5
    fmin.s fa0, fa0, fa1            # fa0 = min(fa0, 1.0)

    # Convert to byte: multiply by 255.0
    lui t5, 0x43800                 # 255.0 in float
    fmv.w.x fa1, t5
    fmul.s fa0, fa0, fa1            # fa0 = fa0 * 255.0

    # Convert to unsigned int
    fcvt.wu.s t5, fa0               # t5 = (uint)fa0

    # Store byte to framebuffer[i]
    add t4, t1, t2                  # t4 = framebuf + i
    sb t5, 0(t4)

    addi t2, t2, 1
    j .Lwrite_pixels

.Lwrite_done:
    ret



# Forward pass through all 1 layers
run_forward_pass:
    addi sp, sp, -16
    sw ra, 12(sp)

    # === Layer 0 ===
    call layer_0_forward

    lw ra, 12(sp)
    addi sp, sp, 16
    ret



# Layer 0: Dense [3 → 2] + relu
layer_0_forward:
    # Input buffer: 0x00150000
    # Output buffer: 0x00153000
    # Weights @ model_base + 0x3C
    # Biases @ model_base + 0x54
    
    # Save callee-saved registers
    addi sp, sp, -32
    sw ra, 28(sp)
    sw s0, 24(sp)
    sw s1, 20(sp)
    sw s2, 16(sp)
    sw s3, 12(sp)
    sw s4, 8(sp)
    
    # Load base addresses
    la s0, model_data_start             # s0 = address of model binary data
    lui s1, 336           # s1 = input buffer
    addi s1, s1, 0
    lui s2, 339          # s2 = output buffer  
    addi s2, s2, 0
    
    # s3 = output index (j), s4 = input index (i)
    li s3, 0                            # j = 0

.L0_outer_loop:
    # Check if j >= output_size
    li t0, 2
    bge s3, t0, .L0_done
    
    # Load bias[j] into fa0 (accumulator)
    li t0, 84
    add t1, s0, t0                      # t1 = model_base + bias_offset
    slli t2, s3, 2                      # t2 = j * 4
    add t1, t1, t2                      # t1 = &bias[j]
    flw fa0, 0(t1)                      # fa0 = bias[j] (accumulator)
    
    # Inner loop: accumulate weights * inputs
    li s4, 0                            # i = 0

.L0_inner_loop:
    # Check if i >= input_size
    li t0, 3
    bge s4, t0, .L0_apply_activation
    
    # Load input[i]
    slli t0, s4, 2                      # t0 = i * 4
    add t1, s1, t0                      # t1 = input_buf + i*4
    flw fa1, 0(t1)                      # fa1 = input[i]
    
    # Load weight[i][j]
    # offset = (i * output_size + j) * 4
    # Compute i * output_size without MUL instruction
    li t1, 0                           # t1 = 0 (accumulator)
    li t2, 2                # t2 = output_size
    li t0, 0                           # t0 = loop counter
.Lmul_0_loop:
    bge t0, s4, .Lmul_0_done
    add t1, t1, t2                      # t1 += output_size
    addi t0, t0, 1
    j .Lmul_0_loop
.Lmul_0_done:
    add t1, t1, s3                      # t1 = i * output_size + j
    slli t1, t1, 2                      # t1 *= 4 (byte offset)
    li t0, 60
    add t1, t1, t0                      # t1 += weights_offset
    add t1, s0, t1                      # t1 = model_base + offset
    flw fa2, 0(t1)                      # fa2 = weight[i][j]
    
    # acc += input[i] * weight[i][j]
    fmul.s fa3, fa1, fa2                # fa3 = input[i] * weight[i][j]
    fadd.s fa0, fa0, fa3                # fa0 += fa3
    
    addi s4, s4, 1                      # i++
    j .L0_inner_loop

.L0_apply_activation:
    # Apply ReLU: max(fa0, 0.0)
    fmv.w.x fa1, zero                   # fa1 = 0.0
    fmax.s fa0, fa0, fa1                # fa0 = max(fa0, 0.0)
    
    # Store output[j] = fa0
    slli t0, s3, 2                      # t0 = j * 4
    add t1, s2, t0                      # t1 = output_buf + j*4
    fsw fa0, 0(t1)                      # output[j] = fa0
    
    addi s3, s3, 1                      # j++
    j .L0_outer_loop

.L0_done:
    # Restore callee-saved registers
    lw ra, 28(sp)
    lw s0, 24(sp)
    lw s1, 20(sp)
    lw s2, 16(sp)
    lw s3, 12(sp)
    lw s4, 8(sp)
    addi sp, sp, 32
    ret



# Sigmoid piecewise linear approximation
# Input: fa0 (x value)
# Output: fa0 (sigmoid(x))
sigmoid_piecewise:
    # Save registers
    addi sp, sp, -16
    sw ra, 12(sp)
    fsw fa1, 8(sp)
    fsw fa2, 4(sp)
    
    # Load constants
    lui t0, 0xC0000          # -2.0 in float
    fmv.w.x fa1, t0
    lui t0, 0x40000          # 2.0 in float
    fmv.w.x fa2, t0
    
    # if x <= -2.0: return 0.0
    fle.s t0, fa0, fa1
    beq t0, zero, .Lsig_check_mid_neg
    fmv.w.x fa0, zero        # return 0.0
    j .Lsig_done
    
.Lsig_check_mid_neg:
    # if x <= 0.0: return 0.25 + 0.125*x
    fmv.w.x fa1, zero
    fle.s t0, fa0, fa1
    beq t0, zero, .Lsig_check_mid_pos
    
    lui t0, 0x3E000          # 0.125 in float
    fmv.w.x fa1, t0
    fmul.s fa1, fa0, fa1     # 0.125 * x
    lui t0, 0x3E800          # 0.25 in float
    fmv.w.x fa2, t0
    fadd.s fa0, fa2, fa1     # 0.25 + 0.125*x
    j .Lsig_done
    
.Lsig_check_mid_pos:
    # if x <= 2.0: return 0.75 + 0.125*x
    lui t0, 0x40000          # 2.0 in float
    fmv.w.x fa2, t0
    fle.s t0, fa0, fa2
    beq t0, zero, .Lsig_saturate
    
    lui t0, 0x3E000          # 0.125 in float
    fmv.w.x fa1, t0
    fmul.s fa1, fa0, fa1     # 0.125 * x
    lui t0, 0x3F400          # 0.75 in float
    fmv.w.x fa2, t0
    fadd.s fa0, fa2, fa1     # 0.75 + 0.125*x
    j .Lsig_done
    
.Lsig_saturate:
    # x > 2.0: return 1.0
    lui t0, 0x3F800          # 1.0 in float
    fmv.w.x fa0, t0
    
.Lsig_done:
    # Restore registers
    lw ra, 12(sp)
    flw fa1, 8(sp)
    flw fa2, 4(sp)
    addi sp, sp, 16
    ret

