# RISC-V Bootloader: Model Compiler Output
# Generated by model_compiler.py Phase 1
#
# This assembly embeds neural network model weights and biases
# using .incbin directive. The bootloader code (Phase 2) will
# copy this embedded data to correct memory addresses.
#
# Model Type: generator
# Number of Layers: 3
# Binary Data Size: 936636 bytes
#
# Memory Map:
#   0x00000 - 0x0FFFF: Bootloader code and embedded model data
#   0x10000 - 0xF3C7F: Generator model (loaded by bootloader)

.section .data
.align 4
.globl model_data_start


# Model binary data (embedded via .incbin)
# Size: 936636 bytes
# Keep model blob away from framebuffer (0x20000) so framebuffer writes
# cannot corrupt model weights/biases during cyclic inference.
    .org 0x30000
model_data_start:
    .incbin "neural_chargen.s.bin"
model_data_end:

# Calculate total embedded data size
.set model_data_size, model_data_end - model_data_start



# ====== EXECUTION CODE ======


# Main execution loop: Input -> Forward Pass -> Output -> Repeat
# Mimics static_char_gen.c behavior but with neural network
.section .text
.align 4
.globl _start

_start:
    # Initialize stack pointer to safe location (within 1MB, below code/data)
    li sp, 0xF000              # sp = 0x0F000 (61440 bytes)
    
    # Main inference loop (infinite)
inference_loop:
    # Step 1: Read input and map to network input
    # For generator: a0 contains character code (set externally or hardcoded for testing)
    # For now, use a test character 'A' = 65
    # a0 already contains character code (read by emulator)
    call map_input_generator
    
    # Step 2: Run forward pass through all layers
    call run_forward_pass
    
    # Step 3: Map output to framebuffer
    call map_output_generator
    
    # Step 4: Loop back
    j inference_loop
    
    # Unreachable, but include exit for completeness
    li a0, 0
    li a7, 93                    # SYS_exit
    ecall



# Input mapping: Character code (a0) -> Network input
# For generator: one-hot encoding of character
map_input_generator:
    # a0 = character code (0-254)
    # Output: input buffer at 0x00150000

    lui t0, 336
    addi t0, t0, 0

    # Zero out entire input buffer (255 floats)
    li t1, 1020
    xor t2, t2, t2
.Lclear_input:
    beq t2, t1, .Lclear_done
    add t3, t0, t2
    sw zero, 0(t3)
    addi t2, t2, 4
    j .Lclear_input

.Lclear_done:
    # Set input[char_code] = 1.0
    # Validate a0 is in range [0, 254]
    li t1, 255
    bgeu a0, t1, .Linput_done

    slli t1, a0, 2                  # t1 = char_code * 4
    add t1, t0, t1                  # t1 = input_buf + offset
    lui t2, 0x3F800                 # t2 = 1.0 in float
    sw t2, 0(t1)                    # input[char_code] = 1.0

.Linput_done:
    ret



# Output mapping: Network output -> Framebuffer pixels
# For generator: convert 400 floats to grayscale pixels
map_output_generator:
    # Read from output buffer at 0x00153000
    # Write to framebuffer at 0x00020000

    lui t0, 339
    addi t0, t0, 0
    lui t1, 32

    li t2, 0                        # t2 = pixel index
    li t3, 400            # t3 = num pixels (400)

.Lwrite_pixels:
    bge t2, t3, .Lwrite_done

    # Load float output[i]
    slli t4, t2, 2                  # t4 = i * 4
    add t4, t0, t4                  # t4 = output_buf + i*4
    flw fa0, 0(t4)                  # fa0 = output[i]

    # Clamp to [0.0, 1.0]
    fmv.w.x fa1, zero
    fmax.s fa0, fa0, fa1            # fa0 = max(fa0, 0.0)
    lui t5, 0x3F800                 # 1.0 in float
    fmv.w.x fa1, t5
    fmin.s fa0, fa0, fa1            # fa0 = min(fa0, 1.0)

    # Convert to byte: multiply by 255.0
    lui t5, 0x43800                 # 255.0 in float
    fmv.w.x fa1, t5
    fmul.s fa0, fa0, fa1            # fa0 = fa0 * 255.0

    # Convert to unsigned int
    fcvt.wu.s t5, fa0               # t5 = (uint)fa0

    # Store byte to framebuffer[i]
    add t4, t1, t2                  # t4 = framebuf + i
    sb t5, 0(t4)

    addi t2, t2, 1
    j .Lwrite_pixels

.Lwrite_done:
    ret



# Forward pass through all 3 layers
run_forward_pass:
    addi sp, sp, -16
    sw ra, 12(sp)

    # === Layer 0 ===
    call layer_0_forward

    # === Layer 1 ===
    call layer_1_forward

    # === Layer 2 ===
    call layer_2_forward

    lw ra, 12(sp)
    addi sp, sp, 16
    ret



# Layer 0: Dense [255 → 256] + relu
layer_0_forward:
    # Input buffer: 0x00150000
    # Output buffer: 0x00151000
    # Weights @ model_base + 0x7C
    # Biases @ model_base + 0xE3C7C
    
    # Save callee-saved registers
    addi sp, sp, -32
    sw ra, 28(sp)
    sw s0, 24(sp)
    sw s1, 20(sp)
    sw s2, 16(sp)
    sw s3, 12(sp)
    sw s4, 8(sp)
    
    # Load base addresses
    la s0, model_data_start             # s0 = address of model binary data
    lui s1, 336           # s1 = input buffer
    addi s1, s1, 0
    lui s2, 337          # s2 = output buffer  
    addi s2, s2, 0
    
    # s3 = output index (j), s4 = input index (i)
    li s3, 0                            # j = 0

.L0_outer_loop:
    # Check if j >= output_size
    li t0, 256
    bge s3, t0, .L0_done
    
    # Load bias[j] into fa0 (accumulator)
    li t0, 932988
    add t1, s0, t0                      # t1 = model_base + bias_offset
    slli t2, s3, 2                      # t2 = j * 4
    add t1, t1, t2                      # t1 = &bias[j]
    flw fa0, 0(t1)                      # fa0 = bias[j] (accumulator)

    # Initialize weight column walk:
    #   start at weights_offset + j*4, stride by output_size*4 for i++
    li t5, 124
    add t5, s0, t5
    add t5, t5, t2
    li t6, 1024
    
    # Inner loop: accumulate weights * inputs
    li s4, 0                            # i = 0

.L0_inner_loop:
    # Check if i >= input_size
    li t0, 255
    bge s4, t0, .L0_apply_activation
    
    # Load input[i]
    slli t0, s4, 2                      # t0 = i * 4
    add t1, s1, t0                      # t1 = input_buf + i*4
    flw fa1, 0(t1)                      # fa1 = input[i]
    
    # Load weight[i][j] from column-walk pointer t5
    flw fa2, 0(t5)                      # fa2 = weight[i][j]
    
    # acc += input[i] * weight[i][j]
    fmul.s fa3, fa1, fa2                # fa3 = input[i] * weight[i][j]
    fadd.s fa0, fa0, fa3                # fa0 += fa3
    
    # Advance to weight[i+1][j]
    add t5, t5, t6
    addi s4, s4, 1                      # i++
    j .L0_inner_loop

.L0_apply_activation:
    # Apply ReLU: max(fa0, 0.0)
    fmv.w.x fa1, zero                   # fa1 = 0.0
    fmax.s fa0, fa0, fa1                # fa0 = max(fa0, 0.0)
    
    # Store output[j] = fa0
    slli t0, s3, 2                      # t0 = j * 4
    add t1, s2, t0                      # t1 = output_buf + j*4
    fsw fa0, 0(t1)                      # output[j] = fa0
    
    addi s3, s3, 1                      # j++
    j .L0_outer_loop

.L0_done:
    # Restore callee-saved registers
    lw ra, 28(sp)
    lw s0, 24(sp)
    lw s1, 20(sp)
    lw s2, 16(sp)
    lw s3, 12(sp)
    lw s4, 8(sp)
    addi sp, sp, 32
    ret



# Layer 1: Dense [256 → 256] + relu
layer_1_forward:
    # Input buffer: 0x00151000
    # Output buffer: 0x00152000
    # Weights @ model_base + 0x3FC7C
    # Biases @ model_base + 0xE407C
    
    # Save callee-saved registers
    addi sp, sp, -32
    sw ra, 28(sp)
    sw s0, 24(sp)
    sw s1, 20(sp)
    sw s2, 16(sp)
    sw s3, 12(sp)
    sw s4, 8(sp)
    
    # Load base addresses
    la s0, model_data_start             # s0 = address of model binary data
    lui s1, 337           # s1 = input buffer
    addi s1, s1, 0
    lui s2, 338          # s2 = output buffer  
    addi s2, s2, 0
    
    # s3 = output index (j), s4 = input index (i)
    li s3, 0                            # j = 0

.L1_outer_loop:
    # Check if j >= output_size
    li t0, 256
    bge s3, t0, .L1_done
    
    # Load bias[j] into fa0 (accumulator)
    li t0, 934012
    add t1, s0, t0                      # t1 = model_base + bias_offset
    slli t2, s3, 2                      # t2 = j * 4
    add t1, t1, t2                      # t1 = &bias[j]
    flw fa0, 0(t1)                      # fa0 = bias[j] (accumulator)

    # Initialize weight column walk:
    #   start at weights_offset + j*4, stride by output_size*4 for i++
    li t5, 261244
    add t5, s0, t5
    add t5, t5, t2
    li t6, 1024
    
    # Inner loop: accumulate weights * inputs
    li s4, 0                            # i = 0

.L1_inner_loop:
    # Check if i >= input_size
    li t0, 256
    bge s4, t0, .L1_apply_activation
    
    # Load input[i]
    slli t0, s4, 2                      # t0 = i * 4
    add t1, s1, t0                      # t1 = input_buf + i*4
    flw fa1, 0(t1)                      # fa1 = input[i]
    
    # Load weight[i][j] from column-walk pointer t5
    flw fa2, 0(t5)                      # fa2 = weight[i][j]
    
    # acc += input[i] * weight[i][j]
    fmul.s fa3, fa1, fa2                # fa3 = input[i] * weight[i][j]
    fadd.s fa0, fa0, fa3                # fa0 += fa3
    
    # Advance to weight[i+1][j]
    add t5, t5, t6
    addi s4, s4, 1                      # i++
    j .L1_inner_loop

.L1_apply_activation:
    # Apply ReLU: max(fa0, 0.0)
    fmv.w.x fa1, zero                   # fa1 = 0.0
    fmax.s fa0, fa0, fa1                # fa0 = max(fa0, 0.0)
    
    # Store output[j] = fa0
    slli t0, s3, 2                      # t0 = j * 4
    add t1, s2, t0                      # t1 = output_buf + j*4
    fsw fa0, 0(t1)                      # output[j] = fa0
    
    addi s3, s3, 1                      # j++
    j .L1_outer_loop

.L1_done:
    # Restore callee-saved registers
    lw ra, 28(sp)
    lw s0, 24(sp)
    lw s1, 20(sp)
    lw s2, 16(sp)
    lw s3, 12(sp)
    lw s4, 8(sp)
    addi sp, sp, 32
    ret



# Layer 2: Dense [256 → 400] + sigmoid
layer_2_forward:
    # Input buffer: 0x00152000
    # Output buffer: 0x00153000
    # Weights @ model_base + 0x7FC7C
    # Biases @ model_base + 0xE447C
    
    # Save callee-saved registers
    addi sp, sp, -32
    sw ra, 28(sp)
    sw s0, 24(sp)
    sw s1, 20(sp)
    sw s2, 16(sp)
    sw s3, 12(sp)
    sw s4, 8(sp)
    
    # Load base addresses
    la s0, model_data_start             # s0 = address of model binary data
    lui s1, 338           # s1 = input buffer
    addi s1, s1, 0
    lui s2, 339          # s2 = output buffer  
    addi s2, s2, 0
    
    # s3 = output index (j), s4 = input index (i)
    li s3, 0                            # j = 0

.L2_outer_loop:
    # Check if j >= output_size
    li t0, 400
    bge s3, t0, .L2_done
    
    # Load bias[j] into fa0 (accumulator)
    li t0, 935036
    add t1, s0, t0                      # t1 = model_base + bias_offset
    slli t2, s3, 2                      # t2 = j * 4
    add t1, t1, t2                      # t1 = &bias[j]
    flw fa0, 0(t1)                      # fa0 = bias[j] (accumulator)

    # Initialize weight column walk:
    #   start at weights_offset + j*4, stride by output_size*4 for i++
    li t5, 523388
    add t5, s0, t5
    add t5, t5, t2
    li t6, 1600
    
    # Inner loop: accumulate weights * inputs
    li s4, 0                            # i = 0

.L2_inner_loop:
    # Check if i >= input_size
    li t0, 256
    bge s4, t0, .L2_apply_activation
    
    # Load input[i]
    slli t0, s4, 2                      # t0 = i * 4
    add t1, s1, t0                      # t1 = input_buf + i*4
    flw fa1, 0(t1)                      # fa1 = input[i]
    
    # Load weight[i][j] from column-walk pointer t5
    flw fa2, 0(t5)                      # fa2 = weight[i][j]
    
    # acc += input[i] * weight[i][j]
    fmul.s fa3, fa1, fa2                # fa3 = input[i] * weight[i][j]
    fadd.s fa0, fa0, fa3                # fa0 += fa3
    
    # Advance to weight[i+1][j]
    add t5, t5, t6
    addi s4, s4, 1                      # i++
    j .L2_inner_loop

.L2_apply_activation:
    # Apply Sigmoid (piecewise linear approximation)
    # fa0 contains input, sigmoid_piecewise returns result in fa0
    call sigmoid_piecewise
    
    # Store output[j] = fa0
    slli t0, s3, 2                      # t0 = j * 4
    add t1, s2, t0                      # t1 = output_buf + j*4
    fsw fa0, 0(t1)                      # output[j] = fa0
    
    addi s3, s3, 1                      # j++
    j .L2_outer_loop

.L2_done:
    # Restore callee-saved registers
    lw ra, 28(sp)
    lw s0, 24(sp)
    lw s1, 20(sp)
    lw s2, 16(sp)
    lw s3, 12(sp)
    lw s4, 8(sp)
    addi sp, sp, 32
    ret



# Sigmoid piecewise linear approximation
# Input: fa0 (x value)
# Output: fa0 (sigmoid(x))
# Formula: clamp(0.5 + x * 0.125, 0, 1) with saturation at x <= -4 and x >= 4
sigmoid_piecewise:
    # Save registers
    addi sp, sp, -16
    sw ra, 12(sp)
    fsw fa1, 8(sp)
    fsw fa2, 4(sp)
    
    # Check x <= -4.0
    lui t0, 0xC0800          # -4.0 in float (0xC0800000)
    fmv.w.x fa1, t0
    fle.s t0, fa0, fa1
    beq t0, zero, .Lsig_check_high
    # x <= -4: return 0.0
    fmv.w.x fa0, zero
    j .Lsig_done
    
.Lsig_check_high:
    # Check x >= 4.0
    lui t0, 0x40800          # 4.0 in float (0x40800000)
    fmv.w.x fa1, t0
    fle.s t0, fa1, fa0       # 4.0 <= x ?
    beq t0, zero, .Lsig_linear
    # x >= 4: return 1.0
    lui t0, 0x3F800          # 1.0 in float
    fmv.w.x fa0, t0
    j .Lsig_done
    
.Lsig_linear:
    # x in [-4, 4]: return 0.5 + x * 0.125
    lui t0, 0x3E000          # 0.125 in float (0x3E000000)
    fmv.w.x fa1, t0
    fmul.s fa1, fa0, fa1     # fa1 = x * 0.125
    lui t0, 0x3F000          # 0.5 in float (0x3F000000)
    fmv.w.x fa2, t0
    fadd.s fa0, fa2, fa1     # fa0 = 0.5 + x * 0.125
    
.Lsig_done:
    # Restore registers
    lw ra, 12(sp)
    flw fa1, 8(sp)
    flw fa2, 4(sp)
    addi sp, sp, 16
    ret

